/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medievil;

import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author tonyc
 */
public class Configuracion extends javax.swing.JFrame {
    Jugador[] jugador = new Jugador[1];
    Vector<Resultado> historial;
    
    /**
     * Creates new form Configuracion
     */
    public Configuracion(Vector<Resultado> historial) {
        initComponents();
        this.historial = historial;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        nomJugador = new javax.swing.JLabel();
        jugador1 = new javax.swing.JTextField();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        nomJugador1 = new javax.swing.JLabel();
        jugador2 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTiempo = new javax.swing.JLabel();
        jJugar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        tiempo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuracion");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nomJugador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomJugador.setText("Jugador 1");

        jugador1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador1ActionPerformed(evt);
            }
        });

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mago", "Guerrero", "Princesa" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Personaje 1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guerrero", "Mago", "Princesa" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Personaje 2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Personaje 3");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Princesa", "Mago", "Guerrero" }));

        nomJugador1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomJugador1.setText("Jugador 2");

        jugador2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mago", "Guerrero", "Princesa" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Personaje 1");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guerrero", "Mago", "Princesa" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Personaje 2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Personaje 3");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Princesa", "Mago", "Guerrero" }));

        jTiempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTiempo.setText("Tiemposeg");

        jJugar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jJugar.setLabel("Jugar");
        jJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJugarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tamaño Tablero");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));

        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nomJugador)
                            .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomJugador1)
                                    .addComponent(jLabel4))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(41, 41, 41)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTiempo)
                                .addGap(63, 63, 63)
                                .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(121, 121, 121)
                        .addComponent(jJugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(nomJugador))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomJugador1)
                            .addComponent(jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jJugar))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJugarActionPerformed
        // TODO add your handling code here:
        addJugador();
        ordenPersonaje();
        
    }//GEN-LAST:event_jJugarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugador1ActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(historial);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    public static javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JButton jJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jTiempo;
    private javax.swing.JTextField jugador1;
    private javax.swing.JTextField jugador2;
    private javax.swing.JLabel nomJugador;
    private javax.swing.JLabel nomJugador1;
    public static javax.swing.JTextField tiempo;
    // End of variables declaration//GEN-END:variables

    private JLabel personaje1_1;
    private JLabel personaje2_1;
    private JLabel personaje3_1;
    private JLabel personaje1_2;
    private JLabel personaje2_2;
    private JLabel personaje3_2;
    
    
private void addJugador(){
    
    Jugador juga = new Jugador();
    
    juga.setNombrejugador1(jugador1.getText());
    juga.setNombrejugador2(jugador2.getText());
    
    if(juga.getNombrejugador1().equalsIgnoreCase(juga.getNombreJugador2())){
        JOptionPane.showMessageDialog(null,"No es posible 2 jugadores con mismo nombre");
        jugador1.setText("");
        jugador2.setText("");
    }
    else{
        
    for(int i=0; i<jugador.length;i++){
        if(jugador[i]==null){
            jugador[i]=juga;
        System.out.println("Jugador 1: "+jugador[i].getNombrejugador1());
        System.out.println("Jugador 2: "+jugador[i].getNombreJugador2());
        }
    }
    }
}

private void ordenPersonaje(){
    
    //Personaje perso = new Personaje();
    
    personaje1_1 = new JLabel();
    personaje2_1 = new JLabel();
    personaje3_1 = new JLabel();
    personaje1_2 = new JLabel();
    personaje2_2 = new JLabel();
    personaje3_2 = new JLabel();
    
    personaje1_1.setText(jComboBox.getSelectedItem().toString());
    personaje2_1.setText(jComboBox1.getSelectedItem().toString());
    personaje3_1.setText(jComboBox3.getSelectedItem().toString());
    personaje1_2.setText(jComboBox4.getSelectedItem().toString());
    personaje2_2.setText(jComboBox5.getSelectedItem().toString());
    personaje3_2.setText(jComboBox6.getSelectedItem().toString());
    
    if(personaje1_1.getText().equals(personaje2_1.getText())||personaje1_1.getText().equals(personaje3_1.getText())||
            personaje2_1.getText().equals(personaje3_1.getText())){
        
        JOptionPane.showMessageDialog(null,"Jugador 1, No es posible elegir 2 Personajes iguales");
    }
    else if(personaje1_2.getText().equals(personaje2_2.getText())||personaje1_2.getText().equals(personaje3_2.getText())||
            personaje2_2.getText().equals(personaje3_2.getText())){
        
        JOptionPane.showMessageDialog(null,"Jugador 2, No es posible elegir 2 Personajes iguales");
        
    }
    else{
        System.out.println("personaje1: "+personaje1_1.getText());
        System.out.println("personaje2: "+personaje2_1.getText());
        System.out.println("personaje3: "+personaje3_1.getText());
        System.out.println("personaje1: "+personaje1_2.getText());
        System.out.println("personaje2: "+personaje2_2.getText());
        System.out.println("personaje3: "+personaje3_2.getText());
    }
    Jugador juganew = new Jugador(jugador1.getText().toString(), jugador2.getText().toString());

    Personaje personaje1juga1, personaje2juga1, personaje3juga1, personaje1juga2, personaje2juga2, personaje3juga2;
    
    Vector<Personaje> personajes1 = new Vector<>();
    Vector<Personaje> personajes2 = new Vector<>();

    
    //personajes jugador 1
        if(jComboBox.getSelectedItem().toString().equals("Guerrero")){
            personaje1juga1 = new Guerrero();
        }else if(jComboBox.getSelectedItem().toString().equals("Mago")){
            personaje1juga1 = new Mago();
        }else{
            personaje1juga1 = new Princesa();
        }
            personajes1.add(personaje1juga1);
    
        if(jComboBox1.getSelectedItem().toString().equals("Guerrero")){
            personaje2juga1 = new Guerrero();
        }else if(jComboBox1.getSelectedItem().toString().equals("Mago")){
            personaje2juga1 = new Mago();
        }else{
            personaje2juga1 = new Princesa();
        }
            personajes1.add(personaje2juga1);
    
        if(jComboBox3.getSelectedItem().toString().equals("Guerrero")){
            personaje3juga1 = new Guerrero();
        }else if(jComboBox3.getSelectedItem().toString().equals("Mago")){
            personaje3juga1 = new Mago();
        }else{
            personaje3juga1 = new Princesa();
        }
            personajes1.add(personaje3juga1);
    
    //personajes jugador 2
        if(jComboBox4.getSelectedItem().toString().equals("Guerrero")){
            personaje1juga2 = new Guerrero();
        }else if(jComboBox4.getSelectedItem().toString().equals("Mago")){
            personaje1juga2 = new Mago();
        }else{
            personaje1juga2 = new Princesa();
        }
            personajes2.add(personaje1juga2);
    
        if(jComboBox5.getSelectedItem().toString().equals("Guerrero")){
            personaje2juga2 = new Guerrero();
        }else if(jComboBox5.getSelectedItem().toString().equals("Mago")){
            personaje2juga2 = new Mago();
        }else{
            personaje2juga2 = new Princesa();
        }
            personajes2.add(personaje2juga2);
    
        if(jComboBox6.getSelectedItem().toString().equals("Guerrero")){
            personaje3juga2 = new Guerrero();
        }else if(jComboBox6.getSelectedItem().toString().equals("Mago")){
            personaje3juga2 = new Mago();
        }else{
            personaje3juga2 = new Princesa();
        }
            personajes2.add(personaje3juga2);
    
        juganew.setPersonajes1(personajes1);
        juganew.setPersonajes2(personajes2);
    
    areaJuego vj = new areaJuego(juganew,historial, Integer.parseInt(jComboBox7.getSelectedItem().toString())); 
    vj.setVisible(true);
    this.dispose();
}

}
